services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: webhook_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webhook-service

volumes:
  db_data:
networks:
  webhook-service:
    driver: bridge
